### ISSUE TITLE
Update project names in subdataset cards on home page

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#15]
From @mih: It would make sense to say "A01 - title" instead of just A01 -- I don't know if these are directories names (strictly)

**Comment by jsheunis** [comment]
These are currently, strictly, taken from the directory names of subdataset paths, yes. `datalad-catalog` could be updated to also allow the inclusion of an additional title string next to the derived directory name...

In the short term, a custom fix in the sfb catalog metadata could be to update the subdataset paths to include the project titles.

**Comment by mslw** [comment]
So the subdataset names are picked up by metalad core extractor (running on the top level dataset) and then go through translator (probably unchanged), correct?

> In the short term, a custom fix in the sfb catalog metadata could be to update the subdataset paths to include the project titles.

Which means git mv'ing everything in the superdataset, right (so that we don't go back to the old names whenever something changes)?

**Comment by jsheunis** [comment]
> So the subdataset names are picked up by metalad core extractor (running on the top level dataset) and then go through translator (probably unchanged), correct?

Not completely unchanged. The translator parses the `hasParts` field in the extracted metadata in order to get submodules, which have relative paths wrt the superdataset (`dataset_path`). The paths are used to populate the list `dirs_from_path` and the last element is used for display and filtering purposes on the dataset page.

@mslw  I.e. an easy (and sfb-catalog-specific) fix would be to just update the `dirs_from_path` field in each element in the `subdatasets` field in the superdataset's metadata file.

**Comment by mslw** [comment]
> @mslw I.e. an easy (and sfb-catalog-specific) fix would be to just update the `dirs_from_path` field in each element in the `subdatasets` field in the superdataset's metadata file.

Thanks for the pointer.

FTR: 

Doing so in the medatada that is fed to `catalog add` makes no change, because `catalog add` (and, more specifically, `datalad_catalog::meta_item::MetaItem.process_dataset`) overrides the `dirs_from_path` key. So I am assuming you mean editing the file *produced* by `datalad catalog add`.

I don't want to do that for two reasons: a) ATM I don't know what is the file hierarchy in the generated catalog (`<dataset_id>/<dataset_version>/<?>/<?>`) or whether it is reported in add results b) in the generated catalog a dataset has both "children" and "subdatasets" with largely overlapping properties.

So if I go for a fix to this issue, I will edit "name" in the metadata that comes from translator, before it goes into `catalog add`.

For a long-term solution, we can think later.

**Comment by mslw** [comment]
Hmm, looks like we've added a list of project names in d22513e91ee915b512ec080c5a9203ed04053579 but we are not using it. Currently, `code/extract_selected` would be the likely place to use it, as it doubles as the superdataset updater script.

**Comment by mslw** [comment]
Superdataset updater script is now `extract_superdataset.py`. The issue remains to be addressed, probably in the way outlined above.

**Comment by mslw** [comment]
We no longer use project datasets.
