### ISSUE TITLE
DOI link on publication page does not resolve correctly

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#23]
E.g.: https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/945795a4-f4d0-43dc-b51a-e73a79ae8d47/7e8814fb39bfb7e6c72340c7c516f46896a2f529

On the “Publications” tab, on the only card on that tab, the DOI link does not resolve correctly. It should go to https://doi.org/10.3390/genes14020454, which it doesn’t.

Ideally, javascript code should be able to parse and/or prepend the required pieces in order for the link to resolve correctly.

**Comment by mslw** [comment]
In this particular case, the DOI came from `datacite.yaml` file where it was specified as:

``` yaml
references:
  -
    id: "doi:10.3390/genes14020454"
```

So assuming that is a correct representation (I didn't look up datacite schema). it might rather be an issue for the [translator](https://github.com/mslw/datalad-wackyextra/blob/main/datalad_wackyextra/translators/datacite.py) that I used for translating into catalog schema - at first glance it does a seemingly case-sensitive substitution (`sub(\"DOI:\"; \"https://www.doi.org/\")`), which should be done in a better way.

In any case, the catalog schema would expect the DOI in an actionable link form (`https://doi.org/...`), correct?

**Comment by mslw** [comment]
> In any case, the catalog schema would expect the DOI in an actionable link form (`https://doi.org/...`), correct?

Just tested and confirmed, DOIs need to be in an an actionable link form (`https://doi.org/...`) to display properly.

Two fixes: 
- I will push a manual tweak to catalog metadata to get the current state fixed, and close this issue.
- I will update translators in datalad-wackyextra (https://github.com/mslw/datalad-wackyextra/commit/f10d040de3e507faf039b2d7556c9257e7f95683) and datalad-catalog (TBD), so that future updates will generate correct DOI links. It was the catalog translator that was used in generation process.

Thanks @maswendt @arefks for reporting!
