### ISSUE TITLE
Allow publication to link to a dataset?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/sfb1451-projects-catalog#24]
@maswendt suggested that in the project superdataset page we could link from publication to a related subdataset. It would make it easier to find datasets related to publications, by going project superdataset -> publication -> subdataset. Currently the project superdataset publication list is independent from subdatasets. The relation can be seen only when going the other way around, project superdataset -> subdataset -> publication (and only if the subdataset actually lists the publication in one of its metadata files).

Open questions

1. A publication would probably need to gain a new property, linked dataset.
2. What would be the way to declare publication -> subdataset linkage? Currently, publications displayed in the project superdataset come from RIS / NBIB / crossref-api-json files; we would need a custom representation.
3. Or should we "bubble up" publications from subdatasets into the superdataset during metadata extraction?

Need to think about it.

**Comment by mslw** [comment]
I have concluded that:
- Creating a link between subdataset ('s publications) and superdataset's publication must be done as part of the catalog generation process, not by the catalog itself. This is an additional logic that goes across dataset boundaries.
- Without introducing additional metadata, we should go through project's subdatasets, find publications declared therein, and add them to the project superdataset (presumably treating DOIs as unique IDs to avoid duplicating publications declared explicitly also for the superdataset), i.e. point 3 in the original issue comment.
- To display the information, catalog schema for a publication would need to allow an additional property.
  - A single "related dataset" might be to restrictive: what if a publication uses several datasets? Would a list, or a free-form comment field (that could be filled while generating the entry) be better?
  - An update to the catalog's schema for publication has been suggested, and this change may also be considered as part of it https://github.com/datalad/datalad-catalog/issues/319

In general I think this is a good idea (especially considering that most SFB datasets will indeed be linked to publications, and declare them in metadata - my understanding is that in internal discussions, a desire has been expressed to have dataset publication conditional on article publication). However, being tied to changes in catalog schema, it will not be immediately prioritized.

**Comment by jsheunis** [comment]
I agree, option 3 seems to be the sensible first step here. I made a related comment in the linked issue: https://github.com/sfb1451/tabby-utils/issues/3#issuecomment-1750305635

Regarding the rendering of related datasets on a publication, this is again influenced by short term deliverables vs long term design/functionality.

For the short term, an addition to the `publications` property in the `dataset` schema is probably the sensible way to go. The current structure is as follows:

```json
publications: [
   {
      "type": "",
      "title": "",
      "doi": "",
      "datePublished":,
      "authors": [
          {
              "givenName": "",
              "familyName": "",
              "name": ""
          }
      ],
      "publicationOutlet": ""
  }
]
```

We could consider adding something like a `relatesTo` list, which would be a list of objects. The structure of these objects do not necessarily have to be uniform, but they could e.g. have an identifiable key that gives more meaning. Eg:

```json
publications: [
   {
      "type": "",
      "title": "",
      ...
      "publicationOutlet": ""
      "relatesTo": [
         {
            "type": "dataset",
            "dataset_id": "1234",
            "dataset_version": "abcd"
         }
      ]
  }
]
```

So to display related datasets on a publication, the html/js would look for any object in the `relatesTo` list that has `type==dataset` and this would be rendered as a component (button / icon / whatever) that will link to the related dataset in the same catalog. Alternatively, another identifiable key could also be specified, e.g. `url` that always renders as a link to wherever it points to. Importantly, the first point assumes that the dataset is indeed contained in the same catalog. And perhaps the assumption would need to be made more explicit:

```python
related_items = dataset["publications"].get("relatesTo", [])
for item in related_items:
    if item["type"] == "dataset":
        if "dataset_id" in item and "dataset_version" in item:
            # assume dataset in catalog, link to it
        elif "url" in item:
            # dataset hosted at provided urlm link to it
        else:
            # twiddle your thumbs
```


To be clear, the suggested change would be very specific to the current issue, since the change only relates to publications and datasets. I.e. not widely applicable. Even so, in the context of generating and rendering catalogs from linked and semantic metadata, the `relatesTo` property would likely map easily onto some relationship between the publication and the dataset.

**Comment by mslw** [comment]
> Regarding the rendering of related datasets on a publication, this is again influenced by short term deliverables vs long term design/functionality.

> To be clear, the suggested change would be very specific to the current issue, since the change only relates to publications and datasets. I.e. not widely applicable. Even so, in the context of generating and rendering catalogs from linked and semantic metadata, the relatesTo property would likely map easily onto some relationship between the publication and the dataset.

I agree with that assessment. Adding to that, if we made the change, we would have to re-extract relevant metadata, starting with designing a way to represent/communicate the relation in the project datasets (remember, for project superdatasets the publications come only from explicitly added RIS/NBIB files). Admittedly, there aren't many datasets that are clearly linked to publications in our catalog, but it seems showing that information requires changes on many fronts.

This tells me that we should deprioritize the issue and treat it as conceptual groundwork for long-term-goal implementations?

**Comment by jsheunis** [comment]
Sounds good to me 👍

**Comment by mslw** [comment]
With the project-level datasets now gone from the catalog, this issue is no longer relevant. Publications need to be defined in datasets using standard mechanisms.

I think this use-case remains an interesting avenue for future explorations.
