### ISSUE TITLE
BUG: fix position of "Request Access" button

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#29]
It does not display correctly in relation to the horizontal line if there aren't any other dataset buttons:

<img width="1315" alt="Screenshot 2023-09-25 at 12 42 06" src="https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/10141237/be73eb8f-f655-4e12-b73f-16cea1fbf179">

**Comment by jsheunis** [comment]
addressed in https://github.com/datalad/datalad-catalog/pull/350

**Comment by mslw** [comment]
Closed by 0bbdb3a but I didn't write the commit message properly. This is what it looks like now:

![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/11985212/5f0fec85-c995-4e98-b569-1d2a66cd3e26)

The introduced white space can be a matter of taste - in this example there are no other buttons that would normally go in that line, on the left (wiew on Github, download with DataLad), otherwise it would be consistent with thlose.
