### ISSUE TITLE
Default dataset "tab" is sometimes empty

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#36]
https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/a808f9e1-d638-4771-ae4c-ff21da29151a/272e2844cd7c58dda8dfe288e7831ad2fa9c34b6 shows the "Subdatasets" tab by default. However, there are no subdatasets.

It would be sensible to show the "Content" tab instead, which has plenty of information.

Also see #33 which compounds the UX.

**Comment by mslw** [comment]
FTR, this has some history (see #28 for reference) and a previous catalog fix was recently determined to cause other trouble and reverted: https://github.com/datalad/datalad-catalog/issues/348

**Comment by jsheunis** [comment]
Indeed, there's a lot of history and moving back and forth on this issue.

I would opt for any of these two options:
- keep it as is, i.e. the subdatasets tab is the default tab
- make the content tab the default tab

In either case, no automated switching based in tab content.

The issue in https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/33 should already be solved unless there's some regression. Will comment on the issue.

**Comment by jsheunis** [comment]
I've been thinking about this more and I'm leaning considerably more towards showing the content tab (i.e. the file tree) as the default, since it feels like most users would expect that as the intuitive entrypoint into exploring a dataset.

@mslw @mih thoughts?

**Comment by mslw** [comment]
This would work well for data-datasets (i.e. everything below project level), because whenever they have content we extract a list of it, and when they don't there is nothing to show beyond the description anyway.

For the superdataset (SFB level) and project-datasets, it would be preferable to show the datasets tab. Apart from holding project descriptions, these two levels serve as nothing more as mount points for dataset content. And although subdatasets are included in the content tab too, the presentation in subdatasets tab is better suited for viewing (authors, big title, sometimes doi badge).

That's at least from the perspective of making initial impressions. But I realize this is very much a consequence of the structure we adopted (sfb - projects - actual data-datasets) and hardly something that can generalize to catalog level.

**Comment by jsheunis** [comment]
We could also create an option for it in the catalog configuration? e.g. `default_tab: 'subdatasets'`, and if not specified the default would be content.

**Comment by mslw** [comment]
Desirables

What I (personally) think is desired here is the following: show datasets tab for the first two levels of the dataset tree, show content tab for all below. Reasons in my previous comment.

Another, more general method: show datasets tab if present, show content tab otherwise, would achieve the same, as we are yet to see a nested dataset below project level.

Obstacles

I don't think the configuration option you propose would allow that level of tuning, unless it can be also stored with the dataset metadata (and even then: should it?).

If I understood https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/28 correctly, the problem with "show datasets tab if present" is that the dataset metadata is loaded concurrently, and the catalog cannot easily know whether there are subdatasets to be shown?

**Comment by jsheunis** [comment]
> What I (personally) think is desired here is the following: show datasets tab for the first two levels of the dataset tree, show content tab for all below. Reasons in my previous comment.

To me this translates, in the general case, to a dataset-specific configuration. Only the agent generating the catalog and entries, not the catalog itself, has the full context for what the "first two levels of the dataset tree" might mean. Therefore these could be specified and configured during catalog entry generation.

> I don't think the configuration option you propose would allow that level of tuning, unless it can be also stored with the dataset metadata (and even then: should it?).

This is already possible with dataset-level config specification in a `datalad catalog-add` call, or am I misunderstanding your point here?

> If I understood https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/28 correctly, the problem with "show datasets tab if present" is that the dataset metadata is loaded concurrently, and the catalog cannot easily know whether there are subdatasets to be shown?

Yes true, but for some reason (which could already be described in a related issue or not, I forget) the asynchronous handling of _disabling_ a tab with no subdatasets is different from the asynchronous handling of _showing_ a tab with no subdatasets _in a different position_. I can revisit the relevant issues/PRs and check whether the latter works (I believe it should).

**Comment by jsheunis** [comment]
In the never-ending spirit of moving back and forth between different solutions, here is my next idea:

1. The content tab should be the first tab, subdatasets should be second
2. The content tab should be displayed by default
3. There can be a dataset-level configuration specifying that the subdatasets tab (or any other tab) should be displayed by default
4. There is no auto-detection of which tabs have content and subsequent programmatic tab selection

My reasoning:
- IMO it is a fairly ubiquitous user experience to view a dataset in an online repository and being presented with the dataset-level metadata (title, authors, description, keywords, etc) **as well as the file tree in the same page**. The concept of "subdatasets" is not very common, and relates more to the git/datalad concepts that fewer people would be familiar with. Showing it by default is actually unexpected, and can be confusing.
- It does not makes sense to me to have programmatic detection of tab content/absence and to set the displayed tab accordingly, because this would make for an inconsistent user experience. Sometimes the filetree shows, sometimes the publications tab shows, sometimes something else. This is confusing to a user.
- I can understand the need to sometimes want the subdatasets tab to show by default, for example when the dataset being displayed is the catalog home page and one would want to be able to quickly filter subdatasets and read subdataset summaries without having to navigate to the subdatasets tab first. However, I think this would be a requirement only in a minority of cases (e.g. for one dataset in a catalog of 50 datasets), which is why I think specifying this via configuration makes more sense.

Next step is to see if all of this is actually reliably possible.

**Comment by mslw** [comment]
I think your last two comments taken together are a very reasonable way to go.

> > I don't think the configuration option you propose would allow that level of tuning, unless it can be also stored with the dataset metadata (and even then: should it?).
> 
> This is already possible with dataset-level config specification in a `datalad catalog-add` call, or am I misunderstanding your point here?

Then it is something I must have missed. So, if I understand correctly:

- there's a general setting to, say, "show files tab by default"
- for sfb- and project-superdatasets I can choose datasets to become default when doing `catalog-add`

Can I do that retroactively (for datasets that were already added)? Can you give me a very quick primer / pointer on how to set these configirations?

**Comment by jsheunis** [comment]
with

> This is already possible with dataset-level config specification in a datalad catalog-add call, or am I misunderstanding your point here?

I was referring to the existing way of configuring settings on a dataset-level. I didn't mean to imply that the specific setting for "which-tab-to-display-first" was already implemented, just that it would be an addition to the existing dataset-level settings.

Relatedly, I have already started the work to implement this, locally. I will continue with that now.

The process for catalog generators would be:
- When adding new dataset records to a catalog:
   - By default the content tab will be displayed, even if empty
   - If the added dataset is to be displayed with a different default tab, that should be specified in a dataset-level configuration, i.e. `datalad catalog-add -c my_catalog -m my_metadata_record -F my_config_file` where `my_config_file` would contain something like:
```
{
    ...
    "dataset_options": {
        ...
        "default_tab": "subdatasets",
        ...
    },
    ...
}
```
- the above should only have to be done for new additions
- for updating existing catalog dataset entries to change to a different default tab display:
   - either update the dataset config file to include the `default_tab` property (might need to create a dataset-level config file if one doesn't exist, by copying the catalog-level config file and then updating it with the new property)
   - or delete the entry and then re-add it as explained above
- other existing catalog entries do not need to be updated, their default  "content" tab will automatically be rendered once the javascript changes are applied.
