### ISSUE TITLE
Look at catalog rendering concept from semantic data view

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#46]
![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/136479/df7b48d4-44a2-4c71-8b18-a06c5524982b)

The screenshot below annotates the source of information for the displayed dataset properties, given the conventions declared in https://github.com/mslw/tabby-utils/tree/main/conventions/tby-crc1451v0

For information that is not annotated, I could not find a proper definition.

The color red is used for information where the subject (ie., the described entity is the dataset itself), other colors are used when the entity is different.

Focusing on the "tabs" the following concept presents itself:

- the first two tabs render (parts of) the list of entities that have the `hasPart` relationship with the shown dataset
- "Publications" lists entities that have the `citation` relationship with the shown dataset
- "Funding" lists entities that have the `funding` relationship with the shown dataset
- "SFB1451" is different, because it lists *relationships* of various kinds that entities of different types have with the shown dataset. Some of which are not properly defined.

I am wondering whether we can formulate a concept that would allow for a less rigid mapping of information onto the metadata schema used by the catalog.

Thoughts:

- we need some awareness of the fundamental nature of semantic data: triples -- subject, predicate/relationship, object
- the main subject of a dataset catalog is obviously a `dataset`, but other relevant entities exist. Only some are "common" (persons, organizations, grants, publication), others are highly use case specific (organs, species).
- different entities require different rendering, sometime the same entities needs to be rendered different, depending on the relationship or other context (think an organization being part of an author list; or a subdataset shown as an item in a content tree vs a subdataset summary list)

Ultimately, the Q for me is to which degree the catalog machinery should be able to work with semantic metadata vs. focus on filling labeled slots with their own rigid semantics?

Roughly speaking, it may be feasible to reannotate the screenshot above to something like: "in this `span` any information can appear that has the shown dataset as the subject AND any of the following relationships with that dataset AND associates objects of any of the following type (or objects that have any of the following properties)."

This could possibly be the nature of a catalog-curator provided specification. The JS machinery could them provide a collection of modules to render information in a particular context. Such contexts would be related to rendering structure, e.g.

- item in a list
- briefest textual representation as part of a paragraph
- in a dedicated tab
- as a button
- ...

Each to be rendered entity could be matched against all known renderers, and the best fitting would be selected. Typical renderer would be

- render record `type:DigitalDocument` as a tree node
- render record `type:Person` as an item in a comma-separated text line
- render keywords in a `div`
- ...

**Comment by jsheunis** [comment]
Thanks @mih for these thoughts. They fit very well into https://github.com/datalad/datalad-catalog/issues/341, and you've given concrete words to what I have only been able to describe as:

> Idea 3
> Perhaps the catalog should somehow evolve into something that can just interpret and render any JSON-LD document, or at least those adhering to some convention as described by a given context. This whole concept needs further exploration, and possible a paradigm shift in terms of how metadata is added to a catalog and rendered by it.

and 

> Rendering based on semantic info: IMO this is the long-term ideal. The catalog should be able derive what data type/format any value is from its semantic information, and the catalog should have standard components for rendering the relevant [content]

I agree with your line of reasoning.

**Comment by jsheunis** [comment]
It's going to take (me) a while to make the whole picture make sense in order to start breaking the challenge down into manageable chunks. I'll try and put a few somewhat random thoughts into words:

> This could possibly be the nature of a catalog-curator provided specification

I think this would be a very important part of the approach, and could play a similar role as conventions do in tabby. I was thinking from the perspective of metadata being added to and subsequently rendered in a catalog: how would one know which properties to "accept" into the catalog and which ones to reject/ignore? But a specification could be the format through which such allowed entities are made known, and this would possibly take over the role currently performed by the more rigid schema.

One aim should be to always try to represent a dataset page in the catalog in the most intuitive and user-friendly way possible. The extreme in the other direction would be to just render a list of triples, which would make sense to machines but would frighten humans. So, an intuitive and constant user experience means (to me) that some structural parts of the dataset page in a catalog would always have a specific meaning attached to it, e.g.:
- the name and authors on the top
- some properties displayed in a dedicated section
- some standard components in another dedicated section (e.g. file tree in a tab, along with other tabs)

Therefore, I think in addition to defined rendering structures (e.g. "item in a list, briefest textual representation as part of a paragraph" etc), there would also be the need to define some minimal structural layout to the page and to then specify which entities could be rendered in which minimal structural component.

Another thought I just had would be to improve the way we provide semantic info about data types in the metadata, because this is one way that could directly influence rendering. If both the property and value of an entity carry semantic information (e.g. `name (schema:Name)` = `Stephan (schema:Text)`) and the catalog provides a list of renderable data type definitions, then the value definitions of metadata added to a catalog could directly inform the rendering component. This would mean that the catalog machinery would not (necessarily?) have to maintain a mapping of the data types of allowed entities to particular rendering types.

In the realm of JS and rendering components, VueJS (if we stick with this framework) is basically built around the concept of [custom UI components](https://vuejs.org/guide/essentials/component-basics.html), so this is functionality is already structurally a good match for this approach.

**Comment by jsheunis** [comment]
Since this issue is a thought process for a new design of catalog rendering, albeit with reference to the SFB1451 catalog, I think this issue should be moved over to `datalad-catalog`. @mslw can you do that?

**Comment by mslw** [comment]
I agree; unfortunately issues can only be transferred between repositories owned by the same user or organization account, so our best chance is copy&paste.

**Comment by jsheunis** [comment]
I made you an admin of `datalad-catalog`, does that help?

**Comment by mslw** [comment]
Thanks, but nothing changed. I can't pick any repo outside psychoinformatics-de. If I understand correctly, GitHub draws a boundary for issue transfer at the organization (or user, depending on whether the repo is hosted under user or organization).

**Comment by jsheunis** [comment]
I've linked it explicitly in the relevant issue in catalog, I think we can close it here.
