### ISSUE TITLE
Z03 mri data records contains undesirable `Z03/` top-level directory

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#71]
https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/9964001a-5e8c-5c70-aedb-55141cca07c0/latest

**Comment by mslw** [comment]
This has been fixed in the respective project datasets by adjusting the tabby files (where the file trees were declared). Now both MRI (sub) datasets follow the same structure, `sourcedata/[ NIfTI | DICOM ]/ ...`. Arguably, `sourcedata` level could also be dropped, but it is also logical to keep it (and it was easier to adjust one dataset instead of two).
