### ISSUE TITLE
Dataset backbutton functioning incorrectly for 2nd-level subdataset

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#87]
Specifically `B03/Externally-Cued Movements`

From @mslw 

> Observe the URLs as you: go to the homepage - select B03 - select externally-cued-movements - click the browser's back button (or the catalog back button).
>
> The datasets are: e132ac40 (super) -- d3648891 (B03) -- a808f9e1 (externally-cued-movements).
> The browser URL goes e132ac40 -- d3648891 -- d3648891 although catalog pages update.
> The back button goes from externally-cued-movements back to the superdataset.

My initial response:

> Can confirm that this happens for me as well. I suspect it's because of the added redirect functionality, but I need to do some testing to confirm this. If true, then we'd need a completely different way of navigating the session history. Currently we use the javascript history API and do a simple history.back() when a user presses the custom back button (which does the same as the browser back button). The best idea I have currently would be to keep track of the pages visited in a higher scope than the dataset pages.

Then i did some more testing and it seems specific for that one dataset. The `B03` dataset has 3 subdatasets, of which this problematic dataset is one. The other two datasets do not show the same behaviour, they behave as expected, i.e. back button follows the correct path along the history stack back to the super, and does not go directly to super. So I think my first assessment is incorrect.

I had a look at the console output when navigating to the externally cued movements dataset:

```
VM327:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at a.beforeRouteUpdate (app_component_dataset.js:751:27)
```

I haven't done more, but next step would be to have a look at the externally cued movements dataset metadata to see if there's something broken that causes this syntaxerror issue, and subsequently the history issue.

**Comment by mslw** [comment]
Oh, wow, looks like you're right. I can't look into that dataset specifically right now, but I'll keep it in mind. Thanks for investigating!

**Comment by mslw** [comment]
Like other datasets, Externally-Cued Movements now resides directly below the superdataset level. The back button functions correctly.

I vaguely remember the "Uncaught (in promise) SyntaxError" appearing when I was debugging some other display issues - I think it was not the actual error, just an effect of processing being interrupted earlier by different errors, leaving the displayed dataset JS object in a broken state. The Externally-Cued Movements dataset has some unique features (like a custom notebook for use with Binder) which may uncover bugs / edge cases (and have done so in a different context; all fixed now).

So whatever the *direct* cause for the behavior was, it has been fixed by subsequent updates, and the issue can be closed.
