### ISSUE TITLE
Superdataset citation contains html tags

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/sfb1451-projects-catalog#92]
Clicking the "Cite" button in https://data.sfb1451.de/dataset/e132ac40-30c5-457d-8c7c-0dcbdbb95d9a/907e4d5ed5ddc033a5ba167bff83abbfcff2b60d shows ``<i>`` HTML tags:

![image](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/assets/29738718/e97a4bf2-b3d1-43e7-b75b-370cdd549eac)

**Comment by mslw** [comment]
I think this is a behavior we inherit from DataLad-Catalog and, in a way, DataCite and its CSL processor.

AFAIK, the "cite" button is shown if dataset metadata includes a DOI. When clicked, the [JS code fetches](https://github.com/datalad/datalad-catalog/blob/44ab1da4a7a9720677171092e2c271705cbae416/datalad_catalog/catalog/assets/app_component_dataset.js#L550) a response from `https://doi.org/...` with header set to `Accept: "text/x-bibliography; style=apa"`, and shows the response text.

I'm pretty sure the title in Zenodo does not contain any formatting markers (also, Zenodo displays its own citation without markup), so my guess is the `<i>` tags are coming from Crosscite (who are the DOI registration agency). This is what the response looks like with a plain `curl` call (it contains the tags):

```
❱ curl -L -H "Accept: text/x-bibliography; style=apa" https://doi.org/10.5281/zenodo.10556115
Fink, G., Aswendt, M., Baldermann, J. C., Bender, S., Bergami, M., Büschges, A., Daun, S., Drzezga, A., Erhardt, E., Eickhoff, S., Gatto, G., Grefkes, C., Hanke, M., Hönig, M., Isbrandt, D., Ito, K., Jessen, F., Kloppenburg, P., Kononenko, N., … Wirth, B. (2024). <i>SFB1451 - key mechanisms of motor control in health and disease</i> (Version v20240124) [Data set]. Zenodo. https://doi.org/10.5281/ZENODO.10556115 
```

As a side note - I was more worried about the thing being reported (in your screenshot) as `[computer software]`. I fixed it by hand on Zenodo and the citations are now produced correctly as `[data set]`. I'm not sure if it was due to zenodo not picking `type: dataset` from our CFF file, or due to my mistake when registering the dataset with Zenodo, but it is worth paying attention to whenever I'm cutting a new "release".

Given that the citation is shown as verbatim text, I think we could patch the JS code for this catalog instance to strip html formatting from the response ([ideas in this SO post](https://stackoverflow.com/a/822486)). Is that what you suggest?

**Comment by jsheunis** [comment]
@mslw your analysis and suggestions make sense to me. Makes sense to fix in datalad-catalog core too.

**Comment by jsheunis** [comment]
This issue can be closed once the latest changes from upstream is merged here, since it was addressed in https://github.com/datalad/datalad-catalog/pull/440
